version: "3.8"
services:
  api:
    build: .
    container_name: rest_api_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db



  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rest_api_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
